/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posinterface;

import MySQL.CRUD;
import MySQL.connect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class list extends javax.swing.JFrame {
    
    int take=0;
    int current=0;
    double total=0;
    String operations;
    String[] prodName = new String[100];
    int[] curr = new int[100]; 
    /**
     * Creates new form list
     */
    public list() {
        initComponents();
        Show_Jtable();
    }
    
    public ArrayList<Inventory> getinventoryList()
    {
        ArrayList<Inventory> inventoryList = new ArrayList<Inventory>();
        Connection con = connect.getConnection();
        
        String query = "SELECT * FROM `inventory`";
        Statement st;
        ResultSet rs;
        
        try{
            st = con.createStatement();
            rs = st.executeQuery(query);
            Inventory inventory;
            while(rs.next())
            {
                inventory = new Inventory(rs.getString("product"),rs.getDouble("price"),rs.getInt("quantity"));
                inventoryList.add(inventory);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return inventoryList;
    }
    
    //show data in table
    
    public void Show_Jtable()
    {
        ArrayList<Inventory> list = getinventoryList();
        DefaultTableModel model = (DefaultTableModel)jTableDisplay.getModel();
        Object[] row = new Object[4];
        for(Inventory list1 : list) {
            row[0] = list1.getProdname();
            row[1] = list1.getPrice();
            row[2] = list1.getQuantity();
            model.addRow(row);
        }
    }
    
    //executing Query
    public void executeQuery(String query, String message)
    {
        Connection con = connect.getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if(st.executeUpdate(query) == 1){
                DefaultTableModel model = (DefaultTableModel)jTableDisplay.getModel();
                model.setRowCount(0);
                Show_Jtable();
                JOptionPane.showMessageDialog(null, "Stock "+message+" Successfully");
            }else{
                JOptionPane.showMessageDialog(null, "Stock Not "+message);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SBtn = new javax.swing.JButton();
        Stextfield = new javax.swing.JTextField();
        Bbtn = new javax.swing.JButton();
        Abtn = new javax.swing.JButton();
        Rbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDisplay = new javax.swing.JTable();
        LogOut = new javax.swing.JButton();
        Prod = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        Price = new javax.swing.JLabel();
        Prc = new javax.swing.JTextField();
        Qnty = new javax.swing.JLabel();
        Qnt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier");
        setBackground(java.awt.SystemColor.activeCaption);
        setMinimumSize(new java.awt.Dimension(860, 530));
        setPreferredSize(new java.awt.Dimension(860, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        SBtn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        SBtn.setText("Search");
        getContentPane().add(SBtn);
        SBtn.setBounds(250, 30, 100, 30);

        Stextfield.setText("Enter Keyword");
        Stextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StextfieldActionPerformed(evt);
            }
        });
        getContentPane().add(Stextfield);
        Stextfield.setBounds(30, 30, 210, 30);

        Bbtn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        Bbtn.setText("Buy");
        Bbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Bbtn);
        Bbtn.setBounds(700, 100, 130, 40);

        Abtn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        Abtn.setText("Add");
        Abtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Abtn);
        Abtn.setBounds(550, 80, 130, 40);

        Rbtn.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        Rbtn.setText("Remove");
        Rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Rbtn);
        Rbtn.setBounds(550, 130, 130, 40);

        jTableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "Qnty."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDisplay.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTableDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDisplay);
        if (jTableDisplay.getColumnModel().getColumnCount() > 0) {
            jTableDisplay.getColumnModel().getColumn(0).setResizable(false);
            jTableDisplay.getColumnModel().getColumn(1).setResizable(false);
            jTableDisplay.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 80, 480, 410);

        LogOut.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut);
        LogOut.setBounds(760, 10, 91, 31);

        Prod.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        Prod.setText("Product");
        getContentPane().add(Prod);
        Prod.setBounds(550, 180, 80, 30);

        Pname.setEditable(false);
        Pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnameActionPerformed(evt);
            }
        });
        getContentPane().add(Pname);
        Pname.setBounds(660, 180, 161, 30);

        Price.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        Price.setText("Price");
        getContentPane().add(Price);
        Price.setBounds(550, 220, 80, 30);

        Prc.setEditable(false);
        Prc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrcActionPerformed(evt);
            }
        });
        getContentPane().add(Prc);
        Prc.setBounds(660, 220, 161, 30);

        Qnty.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        Qnty.setText("Quantity");
        getContentPane().add(Qnty);
        Qnty.setBounds(550, 260, 100, 30);

        Qnt.setEditable(false);
        Qnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QntActionPerformed(evt);
            }
        });
        getContentPane().add(Qnt);
        Qnt.setBounds(660, 260, 161, 30);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(550, 300, 270, 190);

        BG.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/posinterface/pie-wallpaper-1.jpg"))); // NOI18N
        BG.setMaximumSize(new java.awt.Dimension(860, 530));
        BG.setMinimumSize(new java.awt.Dimension(860, 530));
        BG.setPreferredSize(new java.awt.Dimension(860, 530));
        getContentPane().add(BG);
        BG.setBounds(0, 0, 860, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StextfieldActionPerformed

    private void BbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbtnActionPerformed
        String product = Pname.getText();
        
        try{
            Connection con = connect.getConnection();
            ResultSet rs = CRUD.selectInventoryQ(con,product);
            
            rs.next();
            
            if(current >= 0){
                String query = "UPDATE `inventory` SET `Quantity` = '"+current+"' WHERE `inventory`.`Product` = '"+product+"'";
                executeQuery(query,"Updated");
                JOptionPane.showMessageDialog(null, "Total is: "+total+"php");
                Pname.setText("");
                Prc.setText("");
                Qnt.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Could not Buy");
            }
            current=0;
            take=0;
            total=0;
            jTextArea1.setText("");
        }catch(Exception e){
            System.out.println(e);
        }        
    }//GEN-LAST:event_BbtnActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void PnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnameActionPerformed

    private void PrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrcActionPerformed

    private void QntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QntActionPerformed

    private void jTableDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDisplayMouseClicked
        //display row in text fields
        int i = jTableDisplay.getSelectedRow();
        TableModel model = jTableDisplay.getModel();
        Pname.setText(model.getValueAt(i,0).toString());
        Prc.setText(model.getValueAt(i,1).toString());
        Qnt.setText(model.getValueAt(i,2).toString());
        current=(int)model.getValueAt(i,2);
    }//GEN-LAST:event_jTableDisplayMouseClicked

    private void AbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbtnActionPerformed
        int i = jTableDisplay.getSelectedRow();
        TableModel model = jTableDisplay.getModel();
        if(0<current){
            take++;
            total = total+(double)model.getValueAt(i,1);
            current--;
            jTextArea1.setText(model.getValueAt(i,0).toString()+"   "+model.getValueAt(i,1).toString()+"   "+take);
        }else{
            JOptionPane.showMessageDialog(null, "Stock not enough to Buy");
        }
    }//GEN-LAST:event_AbtnActionPerformed

    private void RbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnActionPerformed
        int i = jTableDisplay.getSelectedRow();
        TableModel model = jTableDisplay.getModel();
        if(1<take){
            take--;
            total = total-(double)model.getValueAt(i,1);
            current++;
            jTextArea1.setText(model.getValueAt(i,0).toString()+"   "+model.getValueAt(i,1).toString()+"   "+take);
        }else if(take==1){
            take--;
            total = total-(double)model.getValueAt(i,1);
            current++;
            jTextArea1.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Stock not enough to remove");
        }
    }//GEN-LAST:event_RbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abtn;
    private javax.swing.JLabel BG;
    private javax.swing.JButton Bbtn;
    private javax.swing.JButton LogOut;
    private javax.swing.JTextField Pname;
    private javax.swing.JTextField Prc;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Prod;
    private javax.swing.JTextField Qnt;
    private javax.swing.JLabel Qnty;
    private javax.swing.JButton Rbtn;
    private javax.swing.JButton SBtn;
    private javax.swing.JTextField Stextfield;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDisplay;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
